apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeservice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeservice-api
  template:
    metadata:
      labels:
        app: storeservice-api
    spec:
      containers:
      - image: targetelevate/elevate-ss-api:latest
        name: storeservice-api
        imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: storeservice-api-service
spec:
  selector:
    app: storeservice-api
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort
